# CLASSIFICATION VERSION 1
# set clustering parameters
# LIST_OF_CLUSTERING_PARAMETERS:
#   - no_branches
#   - avg_trafo_dis
#   - max_no_of_households_of_a_branch
#   - no_house_connections_per_branch

# set number of clusters
# N_CLUSTERS_KMEDOID: 5
# N_CLUSTERS_KMEANS: 5
# N_CLUSTERS_GMM: 4  # refers to gmm tied

# -------------------------------------------------------------------------------------------

# CLASSIFICATION VERSION 3
# set clustering parameters
# LIST_OF_CLUSTERING_PARAMETERS:
#   - no_branches
#   - avg_trafo_dis
#   - max_no_of_households_of_a_branch

# set number of clusters
# N_CLUSTERS_KMEDOID: 3
# N_CLUSTERS_KMEANS: 6
# N_CLUSTERS_GMM: 5  # refers to gmm tied

# set threshold values
# THRESHOLD_MAX_TRAFO_DIS: 2.5  # cables between trafo and house connection too long
# THRESHOLD_HOUSEHOLDS_PER_BUILDING: 150  # buildings wrongly attributed as residential

# -------------------------------------------------------------------------------------------

# CLASSIFICATION VERSION 4
# set clustering parameters
LIST_OF_CLUSTERING_PARAMETERS:
  - avg_trafo_dis
  - no_house_connections
  - vsw_per_branch
  - no_households

# set number of clusters
N_CLUSTERS_KMEDOID: 5
N_CLUSTERS_KMEANS: 7
N_CLUSTERS_GMM: 7  # refers to gmm tied

# set threshold values
THRESHOLD_MAX_TRAFO_DIS: 2.5  # cables between trafo and house connection too long
THRESHOLD_HOUSEHOLDS_PER_BUILDING: 150  # buildings wrongly attributed as residential
