CLASSIFICATION_VERSION: 1
CLASSIFICATION_VERSION_COMMENT: "describe the idea and parameters of the classification"
CLASSIFICATION_REGION: Bayern
NO_OF_CLUSTERS_ALLOWED: [3, 4, 5, 6, 7]
N_SAMPLES: 7  # default value

REGION_DICT:
  1: Schleswig-Hohlstein
  2: Hamburg
  3: Niedersachsen
  4: Bremen
  5: Nordrhein-Westfalen
  6: Hessen
  7: Rheinland-Pfalz
  8: Baden-Württemberg
  9: Bayern
  10: Saarland
  11: Berlin
  12: Brandenburg
  13: Mecklenburg-Vorpommern
  14: Sachsen
  15: Sachsen-Anhalt
  16: Thüringen

REGIOSTAR7_DICT:
  71: Stadtregion - Metropole
  72: Stadtregion - Regiopole und Großstadt
  73: Stadtregion - Mittelstadt, städtischer Raum
  74: Stadtregion - Kleinstädtischer, dörflicher Raum
  75: Ländliche Region - Zentrale Stadt
  76: Ländliche Region - Städtischer Raum
  77: Ländliche Region - Kleinstädtischer, dörflicher Raum

REGIO7_REGIO5_GEM_DICT:
  71: 51
  72: 52
  73: 53
  75: 53
  76: 54
  74: 55
  77: 55
