LIST_OF_CLUSTERING_PARAMETERS:
  - avg_trafo_dis
  - no_house_connections
  - vsw_per_branch
  - no_households

# set number of clusters
N_CLUSTERS_KMEDOID: 5
N_CLUSTERS_KMEANS: 7
N_CLUSTERS_GMM: 7  # refers to gmm tied

# set threshold values
THRESHOLD_MAX_TRAFO_DIS: 2.5  # cables between trafo and house connection too long
THRESHOLD_HOUSEHOLDS_PER_BUILDING: 150  # buildings wrongly attributed as residential

# list_of_clustering_paramters_thresholds
THRESHOLD_AVG_TRAFO_DIS: 0.115
THRESHOLD_NO_HOUSE_CONNECTIONS: 14.332
THRESHOLD_VSW_PER_BRANCH: 0.258
THRESHOLD_NO_HOUSEHOLDS: 35.316